language: java
sudo: false
before_install:
  - unset GEM_PATH
script: mvn verify
cache:
  directories:
    - '$HOME/.m2/repository'
env:
  - secure: "h08AjZZ0G2A9gHFbUrLNwBgjqj52On0+psV82JAopZxcdynIK2QQ5uDavZKOU/W3rUSUHJvl7pjzZkZgUccJX+iqUXZh7hJxY79nTPSjMNW4Hl9I7qQp1etKZMxfc0x+1ikZVpzbsfpYaypkf8hTYVKVZTcFDg6yueHL+Q2rI0Q="
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == master ]]; then mvn -B package cargo:redeploy -DskipTests=true; fi
